"""rename department

Revision ID: 39abc7febf54
Revises: 4e2438553719
Create Date: 2024-07-07 14:52:04.684281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39abc7febf54'
down_revision = '4e2438553719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###
